version: '2'

services:
  mysql:
    build:
      context: mysql
    container_name: 'spawning-pool'
    restart: 'on-failure'
    environment:
      MYSQL_ROOT_PASSWORD: 'Kerrigan'
      MYSQL_DATABASE: 'zerglings'
    ports:
      - 3306:3306
    volumes:
      - hatchery:/var/run/mysqld
    command: '--default-authentication-plugin=mysql_native_password'
  php:
    build: php
    container_name: lair
    ports:
      - 8080:80
    links:
      - mysql
    environment:
      WORDPRESS_DB_USER: 'root'
      WORDPRESS_DB_PASS: 'Kerrigan'
      WORDPRESS_DB_HOST: 'mysql'
      MYSQL_PORT_3306_TCP: 3306
  phpmyadmin:
    build: phpmyadmin
    container_name: roach-warden
    ports:
      - 8081:80
    links:
      - mysql

volumes:
  hatchery:
