FROM	ubuntu:16.04

LABEL	Author="Monde MBATHA <mmbatha@student.42.fr>"
		# Description="Cutting-edge LAMP stack, based on Ubuntu 16.04 LTS. Includes .htaccess support and popular PHP7 features, including composer and mail() function." \
		# License="Apache License 2.0" \
		# Usage="docker run -d -p [HOST WWW PORT NUMBER]:80 -p [HOST DB PORT NUMBER]:3306 -v [HOST WWW DOCUMENT ROOT]:/var/www/html -v [HOST DB DOCUMENT ROOT]:/var/lib/mysql fauria/lamp" \
		# Version="1.0"
## Clone https://github.com/mmbatha/Docker_Poor_PHP.git myapp
## Create the directory myapp/apache-vhost
## echo "LoadModule proxy_fcgi_module modules/mod_proxy_fcgi.so\n<VirtualHost *:8080>\n\tServerName myapp.example.com\n\tDocumentRoot \"/app\"\n\tProxyPassMatch ^/(.*\\.php(/.*)?)$ fcgi://php-fpm:9000/app/$1\n\t<Directory \"/app\">\n\t\tOptions Indexes FollowSymLinks\n\t\tAllowOverride All\n\t\tRequire all granted\n\t\tDirectoryIndex index.php\n\t</Directory>\n</VirtualHost>" > myapp/apache-vhost/myapp.conf
## cd myapp
## copy docker-compose.yml to myapp
## run docker-compose up -d
